<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TicketManagementService.Domain\TicketManagementService.Domain.csproj" />
  </ItemGroup>
	<ItemGroup>
  <Protobuf Include="Protos\ticket.proto" GrpcServices="Server" />
</ItemGroup>
	<ItemGroup>
	  <Folder Include="Services\" />
	  <Folder Include="UseCases\CommandHandlers\Tickets\" />
	  <Folder Include="UseCases\CommandHandlers\TicketInventories\" />
	  <Folder Include="UseCases\Commands\TicketInventories\" />
	  <Folder Include="UseCases\Commands\Tickets\" />
	  <Folder Include="UseCases\Queries\TicketInventories\" />
	  <Folder Include="UseCases\Queries\Tickets\" />
	  <Folder Include="UseCases\QueryHandlers\TicketInventories\" />
	  <Folder Include="UseCases\QueryHandlers\Tickets\" />
	</ItemGroup>

</Project>
