<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="12.0.0" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.0" />
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.7.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UserManagementService.DataAccessLayer\UserManagementService.DataAccessLayer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="MappingProfiles\" />
    <Folder Include="Queries\Handlers\" />
  </ItemGroup>

</Project>
