<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.30.2" />
    <PackageReference Include="Grpc.AspNetCore" Version="2.71.0" />
    <PackageReference Include="Grpc.Tools" Version="2.71.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
    <PackageReference Include="MongoDB.Bson" Version="3.3.0" />
    <PackageReference Include="MongoDB.Driver.Core" Version="2.30.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Persistance\DbContext\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TicketManagementService.Application\TicketManagementService.Application.csproj" />
    <ProjectReference Include="..\TicketManagementService.Domain\TicketManagementService.Domain.csproj" />
  </ItemGroup>

	<ItemGroup>
		<Protobuf Include="gRPC/Protos/ticket.proto" GrpcServices="Server" Generator="MSBuild:Compile" />
	</ItemGroup>
	
</Project>
